### ISSUE TITLE
Uncaught DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by Lukashev** [zpao/qrcode.react#198] opened 2022-05-24 05:12 UTC
Hello, i try to export canvas to png with embedded image from S3 bucket. I use **file-saver** library for downloading images.
I also tried separately getting resource with crossOrigin="anonymous" setup, not working, then I tried on svg instead canvas, but again, i got png without embedded image. Maybe someone has workaround and can provide possible solution. Thanks in advance.

**Comment by zpao** [comment] 2022-06-24 19:22
Duplicate of #143

**Closed as not planned by zpao** 2022-06-24 19:22 UTC
